#!/bin/sh

# lib/config.js: module.exports = { VERSION: '0.0.9'

cur=$(grep ' VERSION' lib/config.js | cut -d: -f2- | awk '{print $1}')
new=$1

if [ -z $new ]; then
  echo "USAGE: $0 <x.y.z>"
  echo "e.g. $0 0.1.2"
  exit 1
fi

curnoquotes=$(echo $cur | sed "s/'//g")
newwithquotes="'$new'"

if [ "$cur" = "$newwithquotes" ]; then
  echo "new release same as current!"
  exit 1
fi

echo "creating a new release $cur -> $new"

perl -pi -e "s/version: $curnoquotes/version: $new/" seed.yml
perl -pi -e "s/ VERSION: $cur/ VERSION: $newwithquotes/" lib/config.js

kiwi release nodered $new

git commit -m "Bump version to $new" lib/config.js seed.yml
git tag v$new

echo -n "want to push to github now? (y/n) "
read ans
if [ "$ans" == "y" ]; then
  git push
  git push --tags
fi
